### ISSUE TITLE
Reanimate example

### ISSUE THREAD

**Issue by cdupont** [tonyday567/chart-svg#20]
Hello,
thanks for this library.
it would be nice to have an example for animating diagrams. I see there is a plugin: https://hackage.haskell.org/package/chart-svg-0.2.3/docs/Chart-Reanimate.html
But it's not clear for me how to animate the chart... For instance how to animate some part of the chart, such as the labels or line?
Thanks a lot

**Comment by tonyday567** [comment]
Great question!

There's a high level example here: https://github.com/tonyday567/chart-svg/blob/main/app/reanimate-example.hs of basic usage. If you can get that working locally, you're on the way!

The key is to translate your idea to a concrete function of type `double -> ChartSvg`, and then this feeds in to the whole reanimate way of doing things.

So say if you want the hud to fade in, from being transparent.

```
fadeHud :: ChartSvg -> Double -> ChartSvg
fadeHud c x = c & #hudOptions %~ colourHudOptions (setOpac x dark)
```

To animate something is to smoothly change it over time, going from 0 to 1. 
And then, to reanimate, it would be something like:

```
reanimate $
    animChartSvg defaultReanimateConfig (fadeHud lineExample)
```

I'm in the middle of splitting the package into chart-svg and chart-reanimate: it's gotten a bit too big and I'm adding names/labels/classes/ids (haven't worked out the best way yet) to components of a chart, which is a major refactor. Once that happens, you should be able to say something like `rotate (component "ticks")` to be able to to easily do bulk (or individual) changes.

Happy to help with any of this.

**Comment by cdupont** [comment]
Great! I'll try it out.
Regarding adding names, I was a bit skeptic (not very haskelly), but i see that Diagrams does it too: https://diagrams.github.io/doc/manual.html#named-subdiagrams
Cheers

**Comment by tonyday567** [comment]
I think what I really mean is to switch from using lists of charts everywhere to using a Rose tree (Data.Tree in containers). Having non-empty root nodes should be good for a wide class of bugs that the library tends to suffer from.  And when I say names, I meant that chartList :: [Chart] in ChartSvg  might usefully be chartTree :: Tree (Maybe Text, Chart). Very, very haskelly!

**Comment by cdupont** [comment]
Yes, that looks good

**Comment by tonyday567** [comment]
The recent version bump to chart-svg effected this, and the reanimate bit now live in https://github.com/tonyday567/chart-reanimate. I added in some colour testing I've been doing as an example, and am pretty happy with how it's turning out.

If you're still noodling around with this, I'd be happy to help out with anything.
